
params:
  author: "Your Name"
  description: "Documentation for MyDocs"
  showTableOfContents: true

menu:
  main:
    - identifier: "docs"
      name: "Docs"
      url: "/docs/"
      weight: 1
    - identifier: "example"
      name: "Example"
      url: "/docs/example/"
      weight: 2
    - identifier: "shortcodes"
      name: "Shortcodes"
      url: "/docs/shortcodes/"
      weight: 3
    - identifier: "posts"
      name: "Blog Posts"
      url: "/posts/"
      weight: 4

markup:
  goldmark:
    renderer:
      unsafe: true  # Enable raw HTML inside Markdown

taxonomies:
  category: "categories"
  tag: "tags"

outputs:
  home: ["HTML", "RSS", "JSON"]

permalinks:
  posts: "/posts/:slug/"

params:
  examples:
    collapsed:
      enabled: true
      showSubsections: true
    shortcodes:
      enabled: true

module:
  mounts:
    - source: "content"
      target: "content"
    - source: "assets"
      target: "assets"
    - source: "static"
      target: "static"
    - source: "layouts"
      target: "layouts"
